ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: microsoftedge
    version: latest
  - name: android:
    version: 5.0..latest
  - name: iphone
    version: [8.1, 9.0, 10.0]
  - name: safari
    version: 8..latest
